export const auctions = [
    {
      title: "Tristique diam a, enim, eros tellus. Viverra etiam",
      value: 2.55,
      time: "2:41",
      likes: 54,
      bids: 14,
      cover: "/images/auction/Auctionimg1.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Vulputate felis purus viverra morbi facilisi eget",
      value: 3.19,
      time: "2:41",
      likes: 120,
      bids: 35,
      cover: "/images/auction/Auctionimg2.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Dui accumsan leo vestibulum ornare eu",
      value: 1.11,
      time: "22:59",
      likes: 570,
      bids: 101,
      cover: "/images/auction/Auctionimg3.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Senectus adipiscing nascetur accumsan etiam",
      value: 1.63,
      time: "37:01",
      likes: 98,
      bids: 12,
      cover: "/images/auction/Auctionimg4.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Mattis at diam lorem nisl nam sed sociis",
      value: 2.55,
      time: "12:15",
      likes: 540,
      bids: 19,
      cover: "/images/auction/Auctionimg5.png",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Senectus adipiscing nascetur accumsan etiam",
      value: 1.63,
      time: "37:01",
      likes: 98,
      bids: 12,
      cover: "/images/auction/Auctionimg4.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Mattis at diam lorem nisl nam sed sociis",
      value: 2.55,
      time: "12:15",
      likes: 540,
      bids: 19,
      cover: "/images/auction/Auctionimg5.png",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Tristique diam a, enim, eros tellus. Viverra etiam",
      value: 2.55,
      time: "2:41",
      likes: 54,
      bids: 14,
      cover: "/images/auction/Auctionimg1.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Vulputate felis purus viverra morbi facilisi eget",
      value: 3.19,
      time: "2:41",
      likes: 120,
      bids: 35,
      cover: "/images/auction/Auctionimg2.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Dui accumsan leo vestibulum ornare eu",
      value: 1.11,
      time: "22:59",
      likes: 570,
      bids: 101,
      cover: "/images/auction/Auctionimg3.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Senectus adipiscing nascetur accumsan etiam",
      value: 1.63,
      time: "37:01",
      likes: 98,
      bids: 12,
      cover: "/images/auction/Auctionimg4.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Mattis at diam lorem nisl nam sed sociis",
      value: 2.55,
      time: "12:15",
      likes: 540,
      bids: 19,
      cover: "/images/auction/Auctionimg5.png",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Senectus adipiscing nascetur accumsan etiam",
      value: 1.63,
      time: "37:01",
      likes: 98,
      bids: 12,
      cover: "/images/auction/Auctionimg4.jpeg",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
    {
      title: "Mattis at diam lorem nisl nam sed sociis",
      value: 2.55,
      time: "12:15",
      likes: 540,
      bids: 19,
      cover: "/images/auction/Auctionimg5.png",
      profiles: [
        "/images/profiles/profile1.jpeg",
        "/images/profiles/profile2.jpeg",
        "/images/profiles/profile3.png",
        "/images/profiles/profile4.jpeg",
      ],
    },
  ];